version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0.32
    container_name: gojgho-board-v1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=root
    command: [ '--character-set-server=utf8mb4', '--collation-server=utf8mb4_general_ci']
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./init/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql